dist: xenial
language: rust
matrix:
  include:
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
      rust: stable
    - os: linux
      env: TARGET=x86_64-apple-darwin
      rust: stable
    - os: linux
      env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - os: linux
      env: TARGET=x86_64-apple-darwin
      rust: nightly
sudo: true
-env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
addons:
  apt:
    packages:
      - libgtk-3-dev
      - libmount-dev
script:
  - rustc --version
  - cargo build
    # in order to also check tests and non-default crate features, use
  #- cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
