[package]
name = "connect_four"
version = "0.1.0"
authors = ["Ferry Jérémie <ferryjeremie@free.fr>"]

[dependencies]
cairo-rs = "^0"
gdk      = "^0"
rocket          = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "ef4c2fd" }
rocket_codegen  = { git = "https://github.com/SergioBenitez/Rocket.git", rev = "ef4c2fd" }
serde           = "1.0"
serde_derive    = "1.0"
env_logger      = "0.4"
ws              = "0.7"
log = "*"
time = "*"
serde_json = "*"

[dependencies.rocket_contrib]
git              = "https://github.com/SergioBenitez/Rocket.git"
rev              = "ef4c2fd"
default-features = false
features = ["tera_templates", "msgpack"]

[dependencies.gtk]
version = "0.1.3"
features = ["v3_10"]