[package]
name = "connect_four"
version = "0.1.0"
authors = ["Ferry Jérémie <ferryjeremie@free.fr>"]

[dependencies]
cairo-rs = "^0"
gdk      = "^0"
rocket = "0.3.0"
rocket_codegen = "0.3.0"
yansi = "0.3.4"
serde           = "1.0"
serde_derive    = "1.0"
env_logger      = "0.4"
ws              = "0.7.3"
log = "*"
time = "*"
serde_json = "*"
diesel = { version = "1.1.1", features = ["postgres", "sqlite"] }
dotenv = "0.10.0"
uuid = { version = "0.5", features = ["v4"] }

[dependencies.rocket_contrib]
version = "0.3.0"
default-features = false
features = ["tera_templates", "msgpack"]

[dependencies.gtk]
version = "0.3.0"
features = ["v3_10"]

[replace]
"ws:0.7.3" = { path = '../ws-rs' }
